runtime: python310

entrypoint: gunicorn -b :$PORT calorie_predictor:app

env_variables:
  FLASK_ENV: production

automatic_scaling:
  min_instances: 1
  max_instances: 2

handlers:
- url: /static
  static_dir: static/

- url: /.*
  script: auto
